### PR TITLE
Login Page Created

### PR DESCRIPTION
**Pull request by NithinBalaaji**

### CODE REVIEW

**Comment by adwaith007** [comment]
@Meivenkatkumar

**Comment by adwaith007** [comment]
Use fa cdn instead.

**Comment by NithinBalaaji** [comment]
revised

**Comment by Meivenkatkumar** [comment]
use the user model in master. if you want you can use passport-plugin @NithinBalaaji

**Comment by adwaith007** [comment]
This template looks cooler, maybe u can replace the old one with this.

**Comment by adwaith007** [comment]
peace

**Pull request closed without merging**
